
// Action constants
export const SHOW_CUSTOMERS = 'SHOW_CUSTOMERS';
export const SHOW_CUSTOMER_ORDERS = 'SHOW_CUSTOMER_ORDERS';
export const SHOW_CUSTOMER_PRODUCTS = 'SHOW_CUSTOMER_PRODUCTS';
export const SHOW_CUSTOMER_ORDER_PRODUCTS = 'SHOW_CUSTOMER_ORDER_PRODUCTS';
export const SHOW_CUSTOMER_PRODUCTS_SUMMARY = 'SHOW_CUSTOMER_PRODUCTS_SUMMARY';

